name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Toolchain
      run: docker build -t local < .toolchain/Dockerfile
    - name: Run Make
      run: docker run -it -v $PWD:/root/workspace local make
